#!/bin/bash

path="/root/APIQuest"
pidfile="/var/run/APIQuest.pid"

case "$1" in
	start)
		start-stop-daemon -S -m -p "$pidfile" -d "$path" -b --exec python -- main.py
		;;
	stop)
		start-stop-daemon -K -p "$pidfile"
		;;
	restart)
		$0 stop && $0 start
		;;
esac
